version: '2'
services:
  orc:
    build:
      context: ./
      dockerfile: ./dockerfiles/dev.dockerfile
    ports:
      - '4443:4443'
      - '4444:4444'
      - '4445:4445'
    environment:
      - NODE_ENV=development
