version: '2'
services:
  orc:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./bin:/root/orc/bin
      - ./gui:/root/orc/gui
      - ./lib:/root/orc/lib
      - ./test:/root/orc/test
      - ./package.json:/root/orc/package.json
      - ./index.js:/root/orc/index.js
      - ~/.config/orc.dev:/root/.config/orc
    ports:
      - "127.0.0.1:4444:4444"
      - "127.0.0.1:4445:4445"
      - "127.0.0.1:4446:4446"
      - "127.0.0.1:8080:8080"
    environment:
      - .env
